---
name: AmbiHue
version: "2.0.0"
slug: ambihue
description: "ambihue = Ambilight and Hue connected again!"
url: https://github.com/maarnix/ambihue
arch:
  - aarch64
  - amd64
  - armv7
init: false
boot: manual
panel_icon: mdi:television-ambient-light
host_network: true
hassio_api: true
homeassistant_api: true
auth_api: true

options:
  ambilight_tv:
    protocol: "https://"
    ip: "192.168.1.X"
    port: 1926
    api_version: 6
    user: ""
    password: ""
    pairing_pin: ""
    refresh_rate_ms: 0
    idle_refresh_rate_ms: 5000
    transition_smoothing: 0.5
  hue_entertainment_group:
    ip: "192.168.1.X"
    identification: "replace_me"
    rid: "replace_me"
    username: "replace_me"
    app_id: "replace_me"
    client_key: "replace_me"
    swversion: 1972004020
    index: 0
  lights_setup:
    - name: "light1"
      id: 0
      positions: "0,1,2"
    - name: "light2"
      id: 1
      positions: "3,4,5"

schema:
  ambilight_tv:
    protocol: str
    ip: str
    port: int
    api_version: int
    user: str?
    password: str?
    pairing_pin: str?
    refresh_rate_ms: int
    idle_refresh_rate_ms: int
    transition_smoothing: "float?"
  hue_entertainment_group:
    ip: str
    identification: str
    rid: str
    username: str
    app_id: str
    client_key: str
    swversion: int
    index: int
  lights_setup:
    - name: str
      id: int
      positions: str
